# Site
name: 'Social Tech Playbook'
description: 'The Social Tech Playbook for COVID-19 Response is a technology guide for social service agencies responding to the increased demand for basic needs during the coronavirus pandemic.'
logo: 'assets/img/avatar.png'
logo_full: 'assets/img/avatar.png'
favicon: 'assets/img/favicon/favicon.ico'
baseurl: '/playbook'
url: 'https://socialtech.us'
email: 'socialtech@alluma.org'

include: ["_pages"]
permalink: /:title/
future: true

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [
  _posts/template.md,
  README.md,
  package.json,
  grunt.js,
  Gruntfile.js,
  Gruntfile.coffee,
  node_modules,
  vendor/*,
]

# Disqus
disqus_shortname: socialtechus

# Twitter cards
twitter:
  username: SocialTechUs
  card: 'Working to transform social services tech.'

  # Facebook cards
facebook:
  app_id: 598830250979169
  publisher: https://www.facebook.com/socialtechus


# Archives
jekyll-archives:
  enabled: ['categories']
  layout: archive
  permalinks:
    category: '/category/:name/'