# Site
name: 'Social Tech Playbook'
description: 'The Social Services Response Playbook is a technology guide for social service agencies responding to the increased demand for basic needs during the coronavirus pandemic.'
logo: 'assets/img/favicon/favicon-96x96.png'
logo_full: 'assets/img/favicon/favicon-96x96.png'
favicon: 'assets/img/favicon/favicon.ico'
baseurl: '/playbook'
url: 'https://socialtech.us'
email: 'socialtech@alluma.org'

include: ["_pages"]
permalink: /:title/
future: true

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [
  _posts/2020-01-22-template.md,
  README.md,
  package.json,
  grunt.js,
  Gruntfile.js,
  Gruntfile.coffee,
  node_modules
]